In [2]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
pip install ucimlrepo

Requirement already satisfied: ucimlrepo in c:\users\luan lima\appdata\local\programs\python\python310\lib\site-packages (0.0.2)Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.2.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
from ucimlrepo import fetch_ucirepo, list_available_datasets
data = fetch_ucirepo(name='Abalone')
df = pd.DataFrame(data= data.data.original)

In [15]:
def traditional_outlier(df,x):
    q1  =  df[x].quantile(.25)
    q3  =  df[x].quantile(.75)
    iqr = q3-q1
    df['Traditional']  = np.where(df[[x]]<(q1-1.5*iqr),-1,
                         np.where(df[[x]]>(q3+1.5*iqr),-1,1))
    return df

In [16]:
traditional_outlier(df,'Rings')

,Sex,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,Rings,Traditional
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15,1
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7,1
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9,1
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10,1
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7,1
...,...,...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11,1
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10,1
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9,1
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10,1
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12,1

In [17]:
df = df[df['Traditional'] == 1]

In [18]:
df

,Sex,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,Rings,Traditional
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15,1
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7,1
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9,1
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10,1
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7,1
...,...,...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11,1
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10,1
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9,1
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10,1
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12,1

In [19]:
from sklearn.preprocessing import LabelEncoder

# instantiate LabelEncoder
l_encoder = LabelEncoder()

# transform data
df["Sex"] =  l_encoder.fit_transform(df["Sex"])

C:\Users\Luan Lima\AppData\Local\Temp\ipykernel_11612\575407396.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Sex"] =  l_encoder.fit_transform(df["Sex"])

In [20]:
df

,Sex,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,Rings,Traditional
0,2,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15,1
1,2,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7,1
2,0,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9,1
3,2,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10,1
4,1,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7,1
...,...,...,...,...,...,...,...,...,...,...
4172,0,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11,1
4173,2,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10,1
4174,2,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9,1
4175,0,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10,1
4176,2,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12,1

In [21]:
df["Age"] = df["Rings"] + 1.5
df.drop("Rings", axis=1, inplace=True)

C:\Users\Luan Lima\AppData\Local\Temp\ipykernel_11612\3176473394.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Rings"] + 1.5
C:\Users\Luan Lima\AppData\Local\Temp\ipykernel_11612\3176473394.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop("Rings", axis=1, inplace=True)

In [22]:
df

,Sex,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,Traditional,Age
0,2,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,1,16.5
1,2,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,1,8.5
2,0,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,1,10.5
3,2,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,1,11.5
4,1,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,1,8.5
...,...,...,...,...,...,...,...,...,...,...
4172,0,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,1,12.5
4173,2,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,1,11.5
4174,2,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,1,10.5
4175,0,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,1,11.5
4176,2,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,1,13.5

In [23]:

X = df.drop(["Age", "Traditional"], axis=1) 
y = df["Age"]

In [24]:

from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2, 
                                                    random_state=14)

In [25]:
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
from sklearn import metrics
import warnings
warnings.filterwarnings('ignore')

In [26]:

lr = LinearRegression()

lr.fit(X_train,y_train)

LinearRegression()

In [27]:
r_sq = lr.score(X, y)
print('Coeficiente de DeterminaÃ§Ã£o (RÂ²):', r_sq)

Coeficiente de DeterminaÃ§Ã£o (RÂ²): 0.5061862949738428